library(BiocManager)
library(RJSONIO)
bioc_packages <- BiocManager::available()
json_packages <- RJSONIO::toJSON(data.frame(name=bioc_packages), pretty = TRUE)
write(json_packages, file = "json/packages.json")
